Adiel Dos Santos NAscimento - 201504940002

In [7]:
import numpy as np

a = np.array([[1,2,3,4],[0,5,6,7],[0,0,8,9],[0,0,0,10]])
b = np.array([5,4,4,2])

n = len(a)
x = n*[0]
x[n-1] = b[n-1]/a[n-1][n-1]
for i in range(n-2,-1,-1):
    s=0
        
    for j in range(i+1,n):
        s = s + (a[i][j]*x[j])
        x[i] = (b[i] - s) /a[i][i]


print(x)
print(np.linalg.solve(a,b))


[2.995, 0.18999999999999995, 0.275, 0.2]
[2.995 0.19  0.275 0.2  ]


In [15]:
a = np.array([[2,(1),(-3)], [-1,3,(2)], [(3),(1),(-3)]])
b = np.array([-1,12,0])

print("Matriz inicial")
print(a)

n = len(a)
m = n*[0]
    
for k in range(0,n-1):
    for i in range(k+1,n):
        m = a[i][k]/a[k][k]
        a[i][k]=0
        for j in range(k+1,n):
            a[i][j] = a[i][j] - (m*a[k][j])
            b[i] = b[i] - (m*b[k])
        


print("")
print("Matriz final")
print(a)


Matriz inicial
[[ 2  1 -3]
 [-1  3  2]
 [ 3  1 -3]]

Matriz final
[[ 2  1 -3]
 [ 0  3  0]
 [ 0  0  1]]
